import psutil
import os
import time
import smtplib
from email.message import EmailMessage

def send_email(Rec_Email,FilePath):
    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
    msg = EmailMessage()

    app_password = "xfyzomsutbmzawlo"
    msg["From"] = "ajaybhoge0403@gmail.com"
    msg["To"] = Rec_Email
    msg["Subject"] = f"Platform Surveillance Report from Python Script on {timestamp}"

    msg.set_content(
    f"""Jay Ganesh,
    Greetings from Platform Surveillance System.
    Please find attached the latest system log file create on {timestamp}.
    This report contains detailed information about:

    - Running Processes
    - CPU Usage
    - RAM Usage
    - Network Usage (Sent / Recieved Data)

    This is an automated email generated by the surveillance script. Kindly do not reply this email

    Regards,
    Ajay Bhoge
    """
    )
    with open(FilePath,"rb") as f:
        file_data = f.read()
        file_name = os.path.basename(FilePath)

    msg.add_attachment(file_data,maintype = "application", subtype = "octet-stream", filename = file_name)
    smtp = smtplib.SMTP_SSL("smtp.gmail.com",465)
    smtp.login(msg["From"],app_password)
    smtp.send_message(msg)
    smtp.quit()


def ProcessScan():
    # it is use to iterate processes
    listprocess = []

    for proc in psutil.process_iter():
        info = proc.as_dict(attrs = ["pid","name","username","status"])

        info["cpu_percent"] = proc.cpu_percent(None)
        info["memory_percent"] = proc.memory_percent()
        listprocess.append(info)

    return listprocess

def PlatformSurvillence(FolderName,Reciever_Email):
    Border = "-"*50
    Ret = False

    Ret = os.path.exists(FolderName)
    if(Ret == True):
        Ret = os.path.isdir(FolderName)
        if(Ret == False):
            print("Unable to Proceed As folder name is Existing but it is not a directory")
            return
    else:
        os.mkdir(FolderName)
        print(f"Directory for the log file created Successfullly names As {FolderName}")

    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")

    FileName = os.path.join(FolderName,"Marvellous_%s.txt" %timestamp)

    fobj = open(FileName,"w")

    print(f"Log file gets Successfullly Created with Name {FileName}")

    fobj.write(Border+"\n")
    fobj.write("--- Platform Survillence System---\n")
    fobj.write("Log file gets created At :"+timestamp+"\n")
    fobj.write(Border+"\n\n")

    fobj.write("-----------------------System Report---------------------------\n")

    # Process Log
    Data = ProcessScan()

    for info in Data:
        # fobj.write(f"{info}\n")
        fobj.write("PID: %s\n" %info.get("pid"))
        fobj.write("Name: %s\n" %info.get("name"))
        fobj.write("UserName: %s\n" %info.get("username"))
        fobj.write("Status: %s\n" %info.get("status"))   
        fobj.write("CPU Usage: %.2f\n" %info.get("cpu_percent"))
        fobj.write("RAM Usage: %.2f\n" %info.get("memory_percent"))
        fobj.write(Border+"\n\n")

    fobj.write(Border+"\n\n")
    fobj.write("-----------------------End of Log File---------------------------")
    fobj.write(Border+"\n\n")

    fobj.close()

    send_email(Reciever_Email,FileName)
